language: python
sudo: enabled
dist: trusty
group: edge

# whitelist master/development branch only
branches:
  only:
    - master
    - development
    - development_960

python:
  - "3.7"

before_install:
  - sudo apt-get install -y python3.5 python3.5-dev
  - sudo rm -f /usr/bin/python
  - sudo rm -f /usr/bin/python3
  - sudo ln -s /usr/bin/python3.5 /usr/bin/python
  - sudo ln -s /usr/bin/python3.5 /usr/bin/python3

install: sudo ./install/travis_ci/prepare.sh

script: sudo ./run_tests.sh
