language: python
sudo: enabled
dist: trusty
group: edge

# whitelist master/development branch only
branches:
  only:
    - master
    - development
    - development_simple

services:
  - docker

before_install:
  - docker build --build-arg jumpscale_branch=$JUMPSCALEBRANCH -t threefoldtech/js .

script:
  - docker run --name js -w /opt/code/github/threefoldtech/jumpscale_core threefoldtech/js /bin/bash run_tests.sh
