#! /usr/bin/env python3


from Jumpscale import j
j.tools.bash.local.locale_check()
import click

logger = j.logger.get("js_node", force=True)


@click.group()
def cli():
    pass



print(j.core.state.mascot)


#make sure we don't do autopip
# j.core.state.configSetInDict('system','autopip',False)

j.tools.jsloader.generate()


#try:
#print ("WARNING: dockerconfig was not done")
#from Jumpscale import j as h
#h.tools.develop.dockerconfig() #make sure required config/sshkeys are made available to docker or installed in docker
#except:
#    pass
