#!/usr/bin/env python3

import IPython
import rpyc

import sys

if len(sys.argv) == 2:
    host = sys.argv[1]
else:
    host = "localhost"

c = rpyc.classic.connect(host, 18861)

with rpyc.classic.redirected_stdio(c):
    j = c.modules.Jumpscale.Jumpscale()
    j.embed("jsshell@%s" % host)
